name: Release

on:
  release:
    types: [published]
  # TODO: Remove before merging to main — test trigger only
  push:
    branches:
      - ci/add-ecr-publishing

permissions:
  contents: write
  id-token: write

jobs:
  artifacts:
    uses: ./.github/workflows/artifacts.yml
    with:
      version: ${{ github.event.release.tag_name || 'latest' }}
    secrets: inherit
